name: Action Test Windows

on:
  push:
    paths:
      - '.github/workflows/action-test-windows.yaml'
      - 'action.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Run Runtime IaC Action
      uses: stack-spot/runtime-github-action-iac@main
      with:
        FEATURES_LEVEL_LOG: debug
        input_path: iac.yaml